server:
  ssl:
    key-store: classpath:https_keystore.p12
    key-store-password: chujian
    keyStoreType: PKCS12
    keyAlias: 1
  port: 8443
  http-port: 8080
  servlet:
    application-display-name: firstmeet-msservice-gamesinfo
    contextPath: /
  tomcat:
    basedir: "./"
    accesslog:
      enabled: true
      directory: "./logs/access-log"
    customized.enable: true
    accept-count: 200
    max-threads: 200
    min-spare-threads: 50
    max-connections: 10000

spring:
  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

gamesinfo.api.url: 'http://api.tg.16801.com:8848'
gamesinfo.api.url.platformlist: '${gamesinfo.api.url}/platformlist'
gamesinfo.api.url.serverlist: '${gamesinfo.api.url}/serverlist'
gamesinfo.api.url.charlist: '${gamesinfo.api.url}/charlist'
gamesinfo.api.char.list.mock : false

chujian:
   token:
     key:
       public-key-string: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlTulF2dCQQiU4jkQMQHth084/OZcLFGkse6BQ0J5u47TOJ7PGPMAX1iqCrCwgbseDNLjMMpxLuX4ULbpjFrD/FN1uKmXEVwdP9zYCv22hE618XU6j3u0OEfsgZrupv9+lALxGZKyDfDRsjEy5KCXekAOiXDxJEUl/pNYla8MoJ5D9zjjUzUVq8i3pdL42sP9z6LKhtQXtzOiQ22zGST3mMzButpYXK55LHlgqYXb9hjBbcVIsZYP07Q4mt+NlT+x4crYp4Hirjl9rbUmQm7ZoL3GR8ErJnipPqOo7uKCAmwjKnBoRSu5836gG6kLOiSHtCdu8hp96G8sS95oWorflwIDAQAB'
